/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Microproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import jdk.internal.reflect.ConstantPool;

/**
 *
 * @author user
 */
public class f1 extends javax.swing.JFrame {
    String r="Right",w="wrong";
    String bl="Enter blue",re="Enter red",gr="Enter green",ye="Enter yellow",or="Enter orange",pi="Enter pink",bla="Enter black",gra="Enter gray",cy="Enter cyan";
    int score=0;
    int hscore=0;
    static String name="";
    static String pass="";
    
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form f1
     */
    public f1() {
        initComponents();
        con=Connect.connectdb();
        l1.setText(bl);
        score2.setText(Integer.toString(score));
    }
   
    
    public f1(String name,String pass){
    this.name=name;
    this.pass=pass;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        blue = new javax.swing.JButton();
        red = new javax.swing.JButton();
        green = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        yellow = new javax.swing.JButton();
        orange = new javax.swing.JButton();
        pink = new javax.swing.JButton();
        black = new javax.swing.JButton();
        gray = new javax.swing.JButton();
        cyan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hscore1 = new javax.swing.JLabel();
        hscore2 = new javax.swing.JLabel();
        highscorelabel = new javax.swing.JLabel();
        score1 = new javax.swing.JLabel();
        score2 = new javax.swing.JLabel();
        scorelabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 260, 50));

        l2.setFont(new java.awt.Font("Rockwell Condensed", 1, 48)); // NOI18N
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 190, 60));

        blue.setBackground(java.awt.Color.blue);
        blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueActionPerformed(evt);
            }
        });
        getContentPane().add(blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 37, 35));

        red.setBackground(java.awt.Color.red);
        red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redActionPerformed(evt);
            }
        });
        getContentPane().add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 37, 35));

        green.setBackground(java.awt.Color.green);
        green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenActionPerformed(evt);
            }
        });
        getContentPane().add(green, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 37, 35));

        l3.setBackground(new java.awt.Color(255, 255, 255));
        l3.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 210, 59));

        yellow.setBackground(java.awt.Color.yellow);
        yellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowActionPerformed(evt);
            }
        });
        getContentPane().add(yellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 37, 35));

        orange.setBackground(java.awt.Color.orange);
        orange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeActionPerformed(evt);
            }
        });
        getContentPane().add(orange, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 37, 35));

        pink.setBackground(java.awt.Color.pink);
        pink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinkActionPerformed(evt);
            }
        });
        getContentPane().add(pink, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 37, 35));

        black.setBackground(java.awt.Color.black);
        black.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackActionPerformed(evt);
            }
        });
        getContentPane().add(black, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 37, 35));

        gray.setBackground(java.awt.Color.gray);
        gray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayActionPerformed(evt);
            }
        });
        getContentPane().add(gray, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 37, 35));

        cyan.setBackground(java.awt.Color.cyan);
        cyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cyanActionPerformed(evt);
            }
        });
        getContentPane().add(cyan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 37, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Microproject/white.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 210, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Microproject/white.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 170, 60));

        hscore1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hscore1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hscore1.setText("high score");
        getContentPane().add(hscore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 70, 20));

        hscore2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        hscore2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hscore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 80, 50));

        highscorelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Microproject/images/white.jpg"))); // NOI18N
        getContentPane().add(highscorelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 80));

        score1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        score1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score1.setText("SCORE");
        getContentPane().add(score1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 70, 20));

        score2.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        score2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(score2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 90, 60));

        scorelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Microproject/images/white.jpg"))); // NOI18N
        getContentPane().add(scorelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 110, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Microproject/images/white.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 240, 60));

        back.setBackground(new java.awt.Color(102, 204, 0));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Microproject/images/game.jpg"))); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 790, 540));

        jMenu2.setText("OPTIONS");

        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem3.setText("Help");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("EXIT");

        jMenuItem5.setText("Log Out");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem2.setText("Quit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("DELETE");

        jMenuItem4.setText("Delete This Account");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    public void setscore(int s){
    score2.setText(Integer.toString(score));
        if(s>=hscore){
            hscore=s;
            hscore2.setText(Integer.toString(hscore));
             try{
                String sql2="update login set score=? where name=? and password=?"; 
                pst=con.prepareStatement(sql2);
                pst.setString(1, String.valueOf( hscore));
                pst.setString(2, this.name);
                pst.setString(3, this.pass);
                pst.executeUpdate();
                }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);
               }
        }
    }
    
    
    
    private void blueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueActionPerformed
        // TODO add your handling code here:
        l2.setText("blue");
        
        if(l1.getText()==bl){
        l3.setText(r);
        l1.setText(re);
        score++;
        }
        else{
        l3.setText(w);
        score--;
        }
        setscore(score);
    }//GEN-LAST:event_blueActionPerformed

    private void redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redActionPerformed
        // TODO add your handling code here:
        l2.setText("red");
        if(l1.getText()==re){
        l3.setText(r);
        l1.setText(gr);
        score++;
        }
        else{
        l3.setText(w);
        score--;
        }
        setscore(score);
    }//GEN-LAST:event_redActionPerformed

    private void greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenActionPerformed
        // TODO add your handling code here:
        l2.setText("green");
        if(l1.getText()==gr){
        l3.setText(r);
        l1.setText(ye);
        score++;
        }
        else{
        l3.setText(w);
        score--;
        }
        setscore(score);
    }//GEN-LAST:event_greenActionPerformed

    private void yellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowActionPerformed
        // TODO add your handling code here:
        l2.setText("yellow");
        if(l1.getText()==ye){
        l3.setText(r);
        l1.setText(or);
        score++;
        }
        else{
        l3.setText(w);
        score--;
        }
        setscore(score);
    }//GEN-LAST:event_yellowActionPerformed

    private void orangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeActionPerformed
        // TODO add your handling code here:
        l2.setText("orange");
        if(l1.getText()==or){
        l3.setText(r);
        l1.setText(pi);
        score++;
        }
        else{
        l3.setText(w);
        score--;
        }
        setscore(score);
    }//GEN-LAST:event_orangeActionPerformed

    private void pinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinkActionPerformed
        // TODO add your handling code here:
        l2.setText("pink");
        if(l1.getText()==pi){
        l3.setText(r);
        l1.setText(bla);
        score++;
        }
        else{
        l3.setText(w);
        score--;
        }
       setscore(score);
    }//GEN-LAST:event_pinkActionPerformed

    private void blackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackActionPerformed
        // TODO add your handling code here:
        l2.setText("black");
        if(l1.getText()==bla){
        l3.setText(r);
        l1.setText(gra);
        score++;
        }
        else{
        l3.setText(w);
        score--;
        }
        setscore(score);
    }//GEN-LAST:event_blackActionPerformed

    private void grayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayActionPerformed
        // TODO add your handling code here:
        l2.setText("gray");
        if(l1.getText()==gra){
        l3.setText(r);
        l1.setText(cy);
        score++;
        }
        else{
        l3.setText(w);
        score--;
        }
        setscore(score);
    }//GEN-LAST:event_grayActionPerformed

    private void cyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cyanActionPerformed
        // TODO add your handling code here:
        l2.setText("cyan");
        if(l1.getText()==cy){
        l3.setText(r);
        l1.setText(bl);
        score++;
        }
        else{
        l3.setText(w);
        score--;
        }
        setscore(score);
    }//GEN-LAST:event_cyanActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new delete().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f1().setVisible(true);
                login l=new login();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton black;
    private javax.swing.JButton blue;
    private javax.swing.JButton cyan;
    private javax.swing.JButton gray;
    private javax.swing.JButton green;
    private javax.swing.JLabel highscorelabel;
    private javax.swing.JLabel hscore1;
    private javax.swing.JLabel hscore2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JButton orange;
    private javax.swing.JButton pink;
    private javax.swing.JButton red;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    private javax.swing.JLabel scorelabel;
    private javax.swing.JButton yellow;
    // End of variables declaration//GEN-END:variables

    
    
    
}
