/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Microproject;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Muham
 */
public class home extends javax.swing.JFrame {
    int set=0;
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        create = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        play = new javax.swing.JLabel();
        go = new javax.swing.JButton();
        log = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 0));
        create.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create.setText("CREATE");
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });
        getContentPane().add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 130, 60));

        exit.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 0));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("EXIT");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 130, 70));

        play.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        play.setForeground(new java.awt.Color(255, 255, 0));
        play.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        play.setText("PLAY");
        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playMouseClicked(evt);
            }
        });
        getContentPane().add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 190, 100));

        go.setBackground(new java.awt.Color(0, 0, 0));
        go.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        go.setForeground(new java.awt.Color(255, 255, 255));
        go.setText("GO");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        getContentPane().add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 130, 110));

        log.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        log.setForeground(new java.awt.Color(255, 255, 0));
        log.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        log.setText("NOT LOGGED IN YET!! GO AND CREATE FIRST");
        log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logMouseClicked(evt);
            }
        });
        getContentPane().add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 50));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Microproject/images/main2.jpg"))); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseClicked
        // TODO add your handling code here:
       play.setForeground(Color.red);
       exit.setForeground(Color.yellow);
       create.setForeground(Color.yellow);
       set=1;
       
    }//GEN-LAST:event_playMouseClicked

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
        // TODO add your handling code here:
        create.setForeground(Color.red);
        play.setForeground(Color.yellow);
        exit.setForeground(Color.yellow);
        set=2;
    }//GEN-LAST:event_createMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        exit.setForeground(Color.red);
        play.setForeground(Color.yellow);
        create.setForeground(Color.yellow);
        set=3;
    }//GEN-LAST:event_exitMouseClicked

    private void logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logMouseClicked

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
        
        if(set==1){
            new login().setVisible(true);
            dispose();
        }
        else if(set==2){
            new register().setVisible(true);
            dispose();
        }
        else if(set==3){
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "PLEASE SELECT ANY OPTION");
        }
        
    }//GEN-LAST:event_goActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel create;
    private javax.swing.JLabel exit;
    private javax.swing.JButton go;
    private javax.swing.JLabel log;
    private javax.swing.JLabel play;
    // End of variables declaration//GEN-END:variables
}
